language: cpp
sudo: false
before_install:
        - export LD_LIBRARY_PATH=`pwd`/tests/:$LD_LIBRARY_PATH
script:
        - ./make.sh
        - make check
        - cp libcapstone.so bindings/python/
        - cd bindings/python && make check
compiler:
        - clang
        - gcc
