name: Build Source Release

# Trigger whenever a release is created
on:
  release:
    types:
      - created

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Make setup.sh executable
      run: chmod +x debian/setup.sh

    - name: Build Debian Package
      working-directory: ./debian
      run: ./setup.sh ${{ github.event.release.tag_name }}

    - name: Upload debian package to release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: |
          ./debian/*.deb

    - name: archive
      id: archive
      run: |
        VERSION=${{ github.event.release.tag_name }}
        PKGNAME="capstone-$VERSION"
        SHASUM=$PKGNAME.tar.xz.sha256
        mkdir -p /tmp/$PKGNAME
        mv * /tmp/$PKGNAME
        mv /tmp/$PKGNAME .
        TARBALL=$PKGNAME.tar.xz
        tar cJf $TARBALL $PKGNAME
        sha256sum $TARBALL > $SHASUM
        echo "tarball=$TARBALL" >> $GITHUB_OUTPUT
        echo "shasum=$SHASUM" >> $GITHUB_OUTPUT

    - name: Upload tarball and shasum to release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.release.tag_name }}
        files: |
          ${{ steps.archive.outputs.tarball }}
          ${{ steps.archive.outputs.shasum }}
